
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dvh_familie'
version: '1.0.0'
config-version: 2

#vars:
#  periode: 202401
# This setting configures which "profile" dbt uses for this project.
vars:
  # The `p_in_vedtak_periode_yyyymm` variable will be accessible in all resources
  PP_manedsprosessering:
    pp_omp_periode:
    pp_omp_max_vedtaksperiode:

profile: 'dvh_familie'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
#model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
#seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

quoting:
  database: true


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

# on-run-start:
#   - """
#     begin
#         dbms_application_info.set_client_info( client_info => 'Klient_info Familie-DBT');
#         dbms_application_info.set_module( module_name => 'Kjører Team-familie DBT applikasjon med Airflow'
#                                           , action_name => 'Oppretter views i dvh_fam_ef med ved bruk av DBT' );
#     end;
#     """

#on-run-end:
  #- "grant select, delete, update, insert, read on fam_ef_stonad_arena to DVH_FAM_AIRFLOW"
  #- "grant select, delete, update, insert, read on fam_ef_vedtak_arena to DVH_FAM_AIRFLOW"

models:
  +persist_docs:
    relation: true
    columns: true
  #post-hook: 'grant select, read on {{ this }} to DVH_FAM_AIRFLOW'
  dvh_familie:
    marts:
      +materialized: view
    staging:
      +materialized: view
    KS_transformasjon:
      +materialized: view
