dvh_familie:
  target: dev
  outputs:
    dev:
      type: oracle
      protocol: "tcp"
      user: "{{env_var('DBT_ORCL_USER_PROXY')}}"
      pass: "{{env_var('DBT_ORCL_PASS')}}"
      host: "{{env_var('DBT_ORCL_HOST')}}"
      port: 1521
      service: "{{env_var('DBT_ORCL_SERVICE')}}"
      schema: "{{env_var('DBT_ORCL_SCHEMA')}}"
      threads: 7
