version: 2

sources:
  - name: arena_stonad
    description: ''
    schema: DT_p
    tables:
    - name: DIM_F_STONAD_OMRAADE
      description: ''
    - name: dim_maalgruppe_type
      description: ''
    - name: fak_stonad
      descripion: ''
  
  - name: dt_person_arena
    schema: dt_person
    tables:
    - name: dim_person
    - name: dvh_person_ident_off_id_ikke_skjermet
    
  - name: dt_kodeverk_arena
    schema: dt_kodeverk
    tables: 
    - name: dim_kjonn
    
    



